spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youthdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dummy_password     # 내 비번으로 바꾸기
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 엔티티 구조를 기반으로 테이블 자동 생성
    show-sql: true       # 콘솔에 SQL 출력

server:
  port: 8080

youth:
  api-keys: "67467706-2cc0-4026-a027-769fe60f319b,5935bb50-caea-4c0c-a756-40c6058b093a,18656c8b-75fe-42c5-89cb-d9828ff1a9d9,c08b253a-10ac-4892-888c-eae4516e80ee,7bb52b14-b1b9-42e3-bf8b-a9921faa5db7"
